### ISSUE TITLE
`test_insta` fails on Windows

### ISSUE THREAD

**Issue by vvv** [FoxIO-LLC/ja4#10]
`test_insta` unit test fails on Windows even when `tshark.exe` is installed.

### Symptoms

`cargo test -p ja4 test_insta` generates new snapshots (`rust/src/snapshots/*.snap.new`) with empty YAML arrays.
```powershell
cargo test --manifest-path rust/Cargo.toml -p ja4 test_insta
```

### Clues

`check_tshark_version` succeeds. The number of processed packets (`packet_num`) remains zero.

Ordinary run works fine and produces the normal output:
```powershell
cargo run --manifest-path rust/Cargo.toml -p ja4 -- pcap/latest.pcapng
```

**Comment by vvv** [comment]
_(Note to self.)_

To install `tshark.exe`, add this step to `os-check` job in `test.yml` CI workflow:
```yaml
      - name: Install wireshark
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://www.wireshark.org/download/win64/Wireshark-win64-4.0.10.exe" -OutFile "WiresharkInstaller.exe"
          Start-Process -Wait -FilePath ".\WiresharkInstaller.exe" -ArgumentList "/S"

          # Add tshark's location to the system PATH
          $env:Path += ";$env:ProgramFiles\Wireshark"
          [Environment]::SetEnvironmentVariable("Path", $env:Path, [System.EnvironmentVariableTarget]::Machine)

          tshark --version
```
