### ISSUE TITLE
Linux reference implementation QUIC issues?

### ISSUE THREAD

**Issue by satta** [FoxIO-LLC/ja4#3]
I just tried to process various QUIC pcaps with the Linux binary (`binaries/linux/ja4`) and just got an empty response. For example, for [this one](https://www.cloudshark.org/captures/1737557e3427):
```
$ ./binaries/linux/ja4 chrome-cloudflare-quic-with-secrets.pcapng
[]
```
Can the binaries you provide handle QUIC? For pcaps with TLS content like HTTP/2, I get proper results.
Converting from pcapng to pcap with Wireshark didn't help.

**Comment by vvv** [comment]
This problem has been resolved in v0.13.0.

<details>
<summary>Spoiler</summary>

```
❯ ja4 chrome-cloudflare-quic-with-secrets.pcapng
- stream: 0
  transport: tcp
  src: 2001:db8:1::1
  dst: 2606:4700:10::6816:826
  src_port: 57098
  dst_port: 443
  tls_server_name: cloudflare-quic.com
  ja4: t13d1516h2_8daaf6152771_e5627efa2ab1
  ja4s: t130200_1301_234ea6891581
  ja4l_c: 30_64
  ja4l_s: 5749_56
  http:
  - ja4h: ge20nn16enus_0f5a7a41a252_000000000000_000000000000
- stream: 0
  transport: udp
  src: 2001:db8:1::1
  dst: 2606:4700:10::6816:826
  src_port: 50280
  dst_port: 443
  tls_server_name: cloudflare-quic.com
  ja4: q13d0310h3_55b375c5d22e_cd85d2d88918
  ja4s: q130200_1301_234ea6891581
  ja4l_c: 113_64
  ja4l_s: 9285_56
```

</details>

@john-althouse As time permits, please upload the latest binaries. Consider merging #4 first, as it automates the release. See https://github.com/FoxIO-LLC/ja4/pull/4#issuecomment-1744730783
