### ISSUE TITLE
rust crashes against Arkime pcaps

### ISSUE THREAD

**Issue by awick** [FoxIO-LLC/ja4#51]
* CVE-2018-6794.pcap
The application panicked (crashed).
Message:  assertion failed: ja4l_c > 0
Location: ja4/src/time/tcp.rs:181

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

* gre-erspan-vxlan.pcap
The application panicked (crashed).
Message:  assertion failed: sockets == *self || sockets == self.clone().opposite()
Location: ja4/src/stream.rs:305

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

* nflog.pcap
The application panicked (crashed).
Message:  assertion failed: ja4l_c > 0
Location: ja4/src/time/tcp.rs:181

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
* ospf.pcap
The application panicked (crashed).
Message:  assertion failed: sockets == *self || sockets == self.clone().opposite()
Location: ja4/src/stream.rs:305

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

* v6.pcap
The application panicked (crashed).
Message:  assertion failed: sockets == *self || sockets == self.clone().opposite()
Location: ja4/src/stream.rs:305

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

**Comment by vvv** [comment]
@awick Thanks for the bug reports!

Could you please show the output of `tshark --version` and `ja4 --version`?

The Rust app (`ja4`) in this repo parses the output of `tshark -Tpdml`. The schema of this output may change between major `tshark` versions. If your version of tshark is older than 4.0.6, `ja4` should have [refused to start](https://github.com/FoxIO-LLC/ja4/blob/2a8c08b9d3834f9c93608674d16b53cd006d1707/rust/ja4/src/lib.rs#L168-L188).

I ran the latest release of the Rust app (`ja4 0.16.2`) against the mentioned pcap files (taking them from [arkime/arkime](https://github.com/arkime/arkime/tree/67f587d8502a7a5fd2d7a5119f5bd07b8bf087c1/tests/pcap)), but could not reproduce the problem:

```
❯ tshark --version | head -1
TShark (Wireshark) 4.2.1 (v4.2.1-0-gcfe37f471da9).

❯ ja4 --version
ja4 0.16.2

❯ ja4 CVE-2018-6794.pcap
- stream: 0
  transport: tcp
  src: 192.168.235.1
  dst: 192.168.235.136
  src_port: 53649
  dst_port: 8089
  ja4l_c: 0_128
  ja4l_s: 2219_255
  http:
  - ja4h: ge11nn07ruru_6cd0fb54989b_000000000000_000000000000
- stream: 1
  transport: tcp
  src: 192.168.235.1
  dst: 192.168.235.136
  src_port: 53656
  dst_port: 8089
  ja4l_c: 0_128
  ja4l_s: 1513_255
  http:
  - ja4h: ge11nr06ruru_cc6ec9a91856_000000000000_000000000000
- stream: 2
  transport: tcp
  src: 192.168.235.1
  dst: 192.168.235.136
  src_port: 53648
  dst_port: 8089
  ja4l_c: 0_128
  ja4l_s: 1948_255

❯ ja4 gre-erspan-vxlan.pcap
- stream: 0
  transport: tcp
  src: 100.20.9.2
  dst: 100.20.9.1
  src_port: 65174
  dst_port: 80
  ja4l_c: 953_64
  ja4l_s: 997_64

❯ ja4 nflog.pcap
- stream: 0
  transport: tcp
  src: 10.10.10.10
  dst: 52.43.228.156
  src_port: 54064
  dst_port: 80
  ja4l_c: 0_64
  ja4l_s: 5_226
  http:
  - ja4h: ge11nn030000_32287c24fa5b_000000000000_000000000000

❯ ja4 ospf.pcap
[]

❯ ja4 v6.pcap
- stream: 0
  transport: tcp
  src: 3ffe:507:0:1:200:86ff:fe05:80da
  dst: 3ffe:501:410:0:2c0:dfff:fe47:33e
  src_port: 1022
  dst_port: 22
  ja4l_c: 271_64
  ja4l_s: 28494_61
  ja4ssh:
  - c20s20_c18s23_c11s2
  ssh_extras:
    hassh: null
    hassh_server: null
    ssh_protocol_client: SSH-1.5-1.2.26
    ssh_protocol_server: SSH-1.5-1.2.26
    encryption_algorithm: null
```
