### ISSUE TITLE
rust ja4x issues with Arkime pcaps

### ISSUE THREAD

**Issue by awick** [FoxIO-LLC/ja4#52]
These are all missing ja4x output from rust ja4 against files in https://github.com/arkime/arkime/tree/main/tests/pcap

* https3-301-get.pcap (wireshark crashes on this pcap)
* socks-https-example.pcap 
* socks4-https-https.pcap
* ssl-selfsign.pcap

**Comment by vvv** [comment]
Indeed. The app returns `0: Parsing Error: Der(InvalidLength)` for each of those files.

```
❯ ja4x socks4-https.pcap
Error:
   0: Parsing Error: Der(InvalidLength)

Location:
   ja4x/src/main.rs:53

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

**Comment by vvv** [comment]
@awick I'm looking at `socks4-https.pcap` as an example.

<img width="1624" alt="image" src="https://github.com/FoxIO-LLC/ja4/assets/17462/62c9bbbc-fb9b-4dce-8821-82fd6254ca69">

I'll update `ja4x` to handle the input like this gracefully and not fail, but there is no TLS frames to obtain certificates from, hence no JA4X.

**Comment by awick** [comment]
So i'm just using ja4, not ja4x binary, if that matters.

It is https over socks, I guess wireshark doesn't decode it by default

**Comment by vvv** [comment]
> So i'm just using ja4, not ja4x binary, if that matters.

Makes sense. Thanks for clarifying.

> It is https over socks, I guess wireshark doesn't decode it by default

Wireshark needs secrets to [decrypt TLS traffic](https://wiki.wireshark.org/TLS.md#tls-decryption). Secrets can either be [embedded into a capture file](https://wiki.wireshark.org/TLS#embedding-decryption-secrets-in-a-pcapng-file) or stored separately.

**Comment by awick** [comment]
There is no decryption here. This is https over socks

**Comment by awick** [comment]
Let's ignore the socks ones. I am using release build now. and i can see the certs in wireshark

./target/release/ja4 ~/arkime/tests/pcap/ssl-selfsign.pcap
- stream: 0
  transport: tcp
  src: 10.180.152.137
  dst: 10.180.152.137
  src_port: 60101
  dst_port: 4443
  ja4l_c: 5_64
  ja4l_s: 30_64

./target/release/ja4 ~/arkime/tests/pcap/https3-301-get.pcap
- stream: 0
  transport: tcp
  src: 10.180.156.141
  dst: 192.30.252.130
  src_port: 62599
  dst_port: 443
  ja4l_c: 33_64
  ja4l_s: 17805_50

**Comment by vvv** [comment]
@awick That's weird.

```
❯ for f in https3-301-get.pcap socks-https-example.pcap socks4-https.pcap ssl-selfsign.pcap; do echo "--- $f ---"; ja4 $f; done; unset f
--- https3-301-get.pcap ---
- stream: 0
  transport: tcp
  src: 10.180.156.141
  dst: 192.30.252.130
  src_port: 62599
  dst_port: 443
  tls_server_name: www.github.com
  ja4: t10d230100_6a57a6f57151_000000000000
  ja4s: t100200_0005_696072bc484d
  tls_certs:
  - x509:
    - ja4x: 7d5dbb3783b4_59b7510e6266_5e17a2514980
      issuerCountryName: US
      issuerOrganizationName: DigiCert Inc
      issuerOrganizationalUnit: www.digicert.com
      issuerCommonName: DigiCert High Assurance EV CA-1
      subjectBusinessCategory: Private Organization
      subjectMsJurisdictionCountry: US
      subjectMsJurisdictionStateOrProvince: Delaware
      subjectSerialNumber: '5157550'
      subjectStreetAddress: 548 4th Street
      subjectPostalCode: '94107'
      subjectCountryName: US
      subjectStateOrProvinceName: California
      subjectLocalityName: San Francisco
      subjectOrganizationName: GitHub, Inc.
      subjectCommonName: github.com
    - ja4x: 7d5dbb3783b4_7d5dbb3783b4_897f3043ab93
      issuerCountryName: US
      issuerOrganizationName: DigiCert Inc
      issuerOrganizationalUnit: www.digicert.com
      issuerCommonName: DigiCert High Assurance EV Root CA
      subjectCountryName: US
      subjectOrganizationName: DigiCert Inc
      subjectOrganizationalUnit: www.digicert.com
      subjectCommonName: DigiCert High Assurance EV CA-1
  ja4l_c: 33_64
  ja4l_s: 17805_50
--- socks-https-example.pcap ---
- stream: 0
  transport: tcp
  src: 10.180.156.185
  dst: 10.180.156.249
  src_port: 53554
  dst_port: 1080
  tls_server_name: www.example.com
  ja4: t10d230100_6a57a6f57151_000000000000
  ja4s: t100100_0005_bc98f8e001b5
  tls_certs:
  - x509:
    - ja4x: 7d5dbb3783b4_2bab15409345_5e17a2514980
      issuerCountryName: US
      issuerOrganizationName: DigiCert Inc
      issuerOrganizationalUnit: www.digicert.com
      issuerCommonName: DigiCert High Assurance CA-3
      subjectCountryName: US
      subjectStateOrProvinceName: California
      subjectLocalityName: Santa Monica
      subjectOrganizationName: EdgeCast Networks, Inc.
      subjectCommonName: gp1.wac.edgecastcdn.net
    - ja4x: 7d5dbb3783b4_7d5dbb3783b4_c519788dcb01
      issuerCountryName: US
      issuerOrganizationName: DigiCert Inc
      issuerOrganizationalUnit: www.digicert.com
      issuerCommonName: DigiCert High Assurance EV Root CA
      subjectCountryName: US
      subjectOrganizationName: DigiCert Inc
      subjectOrganizationalUnit: www.digicert.com
      subjectCommonName: DigiCert High Assurance CA-3
  ja4l_c: 23_64
  ja4l_s: 210_64
- stream: 2
  transport: tcp
  src: 10.180.156.185
  dst: 10.180.156.249
  src_port: 53555
  dst_port: 1080
  tls_server_name: www.example.com
  ja4: t10d230100_6a57a6f57151_000000000000
  ja4s: t100100_0005_bc98f8e001b5
  tls_certs:
  - x509:
    - ja4x: 7d5dbb3783b4_2bab15409345_5e17a2514980
      issuerCountryName: US
      issuerOrganizationName: DigiCert Inc
      issuerOrganizationalUnit: www.digicert.com
      issuerCommonName: DigiCert High Assurance CA-3
      subjectCountryName: US
      subjectStateOrProvinceName: California
      subjectLocalityName: Santa Monica
      subjectOrganizationName: EdgeCast Networks, Inc.
      subjectCommonName: gp1.wac.edgecastcdn.net
    - ja4x: 7d5dbb3783b4_7d5dbb3783b4_c519788dcb01
      issuerCountryName: US
      issuerOrganizationName: DigiCert Inc
      issuerOrganizationalUnit: www.digicert.com
      issuerCommonName: DigiCert High Assurance EV Root CA
      subjectCountryName: US
      subjectOrganizationName: DigiCert Inc
      subjectOrganizationalUnit: www.digicert.com
      subjectCommonName: DigiCert High Assurance CA-3
  ja4l_c: 22_64
  ja4l_s: 280_64
- stream: 4
  transport: tcp
  src: 10.180.156.185
  dst: 10.180.156.249
  src_port: 53556
  dst_port: 1080
  tls_server_name: www.example.com
  ja4: t10d230100_6a57a6f57151_000000000000
  ja4s: t100100_0005_bc98f8e001b5
  tls_certs:
  - x509:
    - ja4x: 7d5dbb3783b4_2bab15409345_5e17a2514980
      issuerCountryName: US
      issuerOrganizationName: DigiCert Inc
      issuerOrganizationalUnit: www.digicert.com
      issuerCommonName: DigiCert High Assurance CA-3
      subjectCountryName: US
      subjectStateOrProvinceName: California
      subjectLocalityName: Santa Monica
      subjectOrganizationName: EdgeCast Networks, Inc.
      subjectCommonName: gp1.wac.edgecastcdn.net
    - ja4x: 7d5dbb3783b4_7d5dbb3783b4_c519788dcb01
      issuerCountryName: US
      issuerOrganizationName: DigiCert Inc
      issuerOrganizationalUnit: www.digicert.com
      issuerCommonName: DigiCert High Assurance EV Root CA
      subjectCountryName: US
      subjectOrganizationName: DigiCert Inc
      subjectOrganizationalUnit: www.digicert.com
      subjectCommonName: DigiCert High Assurance CA-3
  ja4l_c: 15_64
  ja4l_s: 233_64
--- socks4-https.pcap ---
- stream: 0
  transport: tcp
  src: 10.0.0.1
  dst: 10.0.0.2
  src_port: 50606
  dst_port: 9901
  ja4l_c: 119349_126
  ja4l_s: 40155_52
--- ssl-selfsign.pcap ---
- stream: 0
  transport: tcp
  src: 10.180.152.137
  dst: 10.180.152.137
  src_port: 60101
  dst_port: 4443
  ja4: ts3i230000_6a57a6f57151_000000000000
  ja4s: ts30100_0035_bc98f8e001b5
  tls_certs:
  - x509:
    - ja4x: 7022c563de38_7022c563de38_795797892f9c
      issuerCommonName: molochftw
      subjectCommonName: molochftw
  - x509:
    - ja4x: bbd6cc0fca29_bbd6cc0fca29_795797892f9c
      issuerCommonName: MO
      issuerOrganizationName: LO
      issuerCountryName: CH
      subjectCommonName: MO
      subjectOrganizationName: LO
      subjectCountryName: CH
  ja4l_c: 5_64
  ja4l_s: 30_64
```
